"""initial

Revision ID: 37b96823ca7f
Revises: bcd1bc42215e
Create Date: 2024-07-30 22:04:21.914755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b96823ca7f'
down_revision: Union[str, None] = 'bcd1bc42215e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('action', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_history', 'action')
    # ### end Alembic commands ###
