"""initial

Revision ID: 3f77c956c538
Revises: b60a242b1598
Create Date: 2024-08-10 21:54:28.710286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f77c956c538'
down_revision: Union[str, None] = 'b60a242b1598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_history_user_id'), 'payment_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_ratings_rated_user_id'), 'ratings', ['rated_user_id'], unique=False)
    op.create_index(op.f('ix_transactions_initiator'), 'transactions', ['initiator'], unique=False)
    op.create_index(op.f('ix_transactions_user_for'), 'transactions', ['user_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_for'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_initiator'), table_name='transactions')
    op.drop_index(op.f('ix_ratings_rated_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_payment_history_user_id'), table_name='payment_history')
    # ### end Alembic commands ###
