"""initial

Revision ID: 745d458fc8bc
Revises: e38ed6adf680
Create Date: 2024-07-27 21:35:12.493130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745d458fc8bc'
down_revision: Union[str, None] = 'e38ed6adf680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
