"""initial

Revision ID: 8a8ae11ea7fe
Revises: 37b96823ca7f
Create Date: 2024-08-01 15:14:36.177158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8ae11ea7fe'
down_revision: Union[str, None] = '37b96823ca7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transactions', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'finished_at')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
