"""initial

Revision ID: b60a242b1598
Revises: 96ac503f55eb
Create Date: 2024-08-10 18:10:52.678390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60a242b1598'
down_revision: Union[str, None] = '96ac503f55eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payment_history_user_id_fkey', 'payment_history', type_='foreignkey')
    op.create_foreign_key(None, 'payment_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_initiator_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_creator_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_user_for_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['initiator'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'users', ['creator'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'users', ['user_for'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_for_fkey', 'transactions', 'users', ['user_for'], ['id'])
    op.create_foreign_key('transactions_creator_fkey', 'transactions', 'users', ['creator'], ['id'])
    op.create_foreign_key('transactions_initiator_fkey', 'transactions', 'users', ['initiator'], ['id'])
    op.drop_constraint(None, 'payment_history', type_='foreignkey')
    op.create_foreign_key('payment_history_user_id_fkey', 'payment_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
