"""initial

Revision ID: c0601e066317
Revises: 65f8d2115e99
Create Date: 2024-08-03 20:26:49.863407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0601e066317'
down_revision: Union[str, None] = '65f8d2115e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('creator', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'creator')
    # ### end Alembic commands ###
