# Exported from Render on 2024-10-02T13:45:10Z
services:
- type: web
  name: paymentfreebot
  runtime: python
  repo: https://github.com/Klaxer77/paymentfreebot
  plan: free
  envVars:
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASS
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_HOST
    sync: false
  - key: YOOKASSA_SHOPID
    sync: false
  - key: YOOKASSA_SECRETKEY_SHLUZ
    sync: false
  - key: YOOKASSA_SECRETKEY
    sync: false
  - key: YOOKASSA_AGENTID
    sync: false
  - key: WEB_APP_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: NGROK_TUNNEL_URL
    sync: false
  - key: MODE
    sync: false
  - key: LOG_LEVEL
    sync: false
  - key: COMMISION_PERCENTAGE
    sync: false
  - key: BOT_SECRET_TOKEN
    sync: false
  - key: ALGORITHM
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class
    uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
version: "1"
